return {
  [1] = "LOCKSTEP", -- actually nothing, but guess default is Lockstep
  [2] = "IMMEDIATE",
  [3] = "IMMEDIATE",
  [4] = "IMMEDIATE",
  [5] = "IMMEDIATE",
  [6] = "IMMEDIATE",
  [7] = "IMMEDIATE",
  [8] = "LOCKSTEP",
  [9] = "IMMEDIATE",
  [10] = "IMMEDIATE",
  [11] = "IMMEDIATE",
  [12] = "IMMEDIATE",
  [13] = "IMMEDIATE",
  [14] = "IMMEDIATE",

  --15: ClickNavigateMenuOrEscape
  [15] = "LOCKSTEP",
  [16] = "LOCKSTEP",
  [17] = "LOCKSTEP",
  [18] = "LOCKSTEP",
  [19] = "LOCKSTEP",
  [20] = "LOCKSTEP",
  [21] = "LOCKSTEP",
  [22] = "LOCKSTEP",
  [23] = "LOCKSTEP",
  [24] = "LOCKSTEP",
  [25] = "LOCKSTEP",
  [26] = "LOCKSTEP",
  [27] = "LOCKSTEP",
  [28] = "LOCKSTEP",
  [29] = "LOCKSTEP",
  [30] = "LOCKSTEP",
  [31] = "LOCKSTEP",
  [32] = "LOCKSTEP",
  [33] = "LOCKSTEP",
  [34] = "LOCKSTEP",
  [35] = "LOCKSTEP",
  [36] = "LOCKSTEP",
  [37] = "LOCKSTEP",
  [38] = "LOCKSTEP",
  [39] = "LOCKSTEP",

  -- 40: SetPlayerName
  [40] = "IMMEDIATE",

  [41] = "LOCKSTEP",
  [42] = "LOCKSTEP",
  [43] = "LOCKSTEP",
  [44] = "LOCKSTEP",
  [45] = "LOCKSTEP",

  -- 46: Share desynced hashes
  [46] = "IMMEDIATE",
  [47] = "IMMEDIATE",
  [48] = "IMMEDIATE",
  [49] = "IMMEDIATE",
  [50] = "IMMEDIATE",
  [51] = "IMMEDIATE",
  [52] = "IMMEDIATE",
  [53] = "IMMEDIATE",

  -- 54: game desync
  [54] = "LOCKSTEP",

  [55] = "IMMEDIATE",
  [56] = "IMMEDIATE",
  [57] = "IMMEDIATE",
  [58] = "IMMEDIATE",
  [59] = "IMMEDIATE",
  [60] = "IMMEDIATE",
  [61] = "IMMEDIATE",
  [62] = "IMMEDIATE",
  [63] = "IMMEDIATE",
  [64] = "IMMEDIATE",
  [65] = "IMMEDIATE",
  [66] = "IMMEDIATE",
  [67] = "IMMEDIATE",

  [68] = "LOCKSTEP",
  [69] = "LOCKSTEP",
  [70] = "LOCKSTEP",
  [71] = "LOCKSTEP",
  [72] = "LOCKSTEP",
  [73] = "LOCKSTEP",
  [74] = "LOCKSTEP",
  [75] = "LOCKSTEP",
  [76] = "LOCKSTEP",
  [77] = "LOCKSTEP",
  [78] = "LOCKSTEP",
  [79] = "LOCKSTEP",
  
  [80] = "IMMEDIATE",
  [81] = "IMMEDIATE",
  [82] = "IMMEDIATE",

  [83] = "LOCKSTEP",

  [84] = "IMMEDIATE",
  [85] = "IMMEDIATE",

  [86] = "LOCKSTEP",

  [87] = "IMMEDIATE",
  [88] = "IMMEDIATE",
  [89] = "IMMEDIATE",
  [90] = "IMMEDIATE",
  [91] = "IMMEDIATE",
  [92] = "IMMEDIATE",
  [93] = "IMMEDIATE",
  [94] = "IMMEDIATE",
  [95] = "IMMEDIATE",
  [96] = "IMMEDIATE",

  [97] = "LOCKSTEP",

  [98] = "IMMEDIATE",
  [99] = "IMMEDIATE",
  [100] = "IMMEDIATE",
  [101] = "IMMEDIATE",

  [102] = "LOCKSTEP",

  [103] = "IMMEDIATE",
  [104] = "IMMEDIATE",
  [105] = "IMMEDIATE",
  [106] = "IMMEDIATE",
  [107] = "IMMEDIATE",
  [108] = "IMMEDIATE",
  [109] = "IMMEDIATE",
  [110] = "IMMEDIATE",
  [111] = "IMMEDIATE",
  [112] = "IMMEDIATE",

  [113] = "LOCKSTEP",

  [114] = "IMMEDIATE",
  [115] = "IMMEDIATE",
  [116] = "IMMEDIATE",
  [117] = "IMMEDIATE",
  [118] = "IMMEDIATE",

  [119] = "LOCKSTEP",
}